### PR TITLE
Bookmarks UI improvements

### PR DESCRIPTION
**Pull request by vsopko**

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Thank you for helping out. 

I am not sure I am sold on the new UX the PR delivers.

- It's hard to distinguish between the node coloured because it is bookmarked from the node that is selected. One needs to remember the exact selection colour. I actually think having the default selection border makes more sense.
- Selection background interferes with setting the bookmark colour. It hides it. Thus until the node gets unselected it's impossible to say if the bookmark color was successfully assigned.
- Though I agree that your 'sync' icon is better. I deliberately wanted it to be single-directional because clicking this button syncs only one of the involved parties the tree. That's why I made my own icon for that. But I am afraid it becomes completely unintuitive - it's hard to say what this button means until you pop the tooltip. I will use your image then.

Ironically I also played with it yesterday.

This is the progress:

1.  Make (remove) border of hovered and active nodes rectangles same color as background (like in Git Changes window). It will clean up UI
   _I decided to keep the existing UX for the reasons above._

2. Make bookmarks background under full node, not only behind text. It will fasten visual recognition.
    _done_
    But I will need to update the all node icons to unsure they are not blending too much to the background as they do now.

4. Make bookmarks popup on full node right-click, not ony on text. It's disorienting now.
    _done_
    Only need to address some strange artifact for the node autosizing if the re is no bookmark. 
 
 This is what I have so far (bookmarks-styling branch):
 
 
image

**Comment by vsopko** [comment]
Agreed with "...It's hard to distinguish between the node coloured...". I think the proper way is to remove border from nodes and define 3 colors for each state (like with flat buttons):
1. Default (or "bookmarked")
2. Mouse hovered (slightly brighter then 1)
3. Selected (more brightness then 2)

Also please look that list border was removed (available only on bottom side for expander visual splitting) and expander content slightly padded from top.

In general, it seems to me that everything is clear and the decision is at your discretion

**Comment by oleg-shilo** [comment]
Done.

I decided to keep the existing selection visual effect (with minor layout adjustments) but otherwise, all the suggestions we discussed ended up in the final solution.

image

Thank you for sharing ContextMenu styling. It saved me the time of repeating the IDE styling.

**Comment by oleg-shilo** [comment]
I will be closing this PR as almost all its content is now in the codebase anyway.

**Pull request closed without merging**
