### PR TITLE
Bookmarks marks on editors vertical scrollbar

### PR DESCRIPTION
**Pull request by vsopko**
It would be nice to make this as option (disable/enable) in VS Tools>Options>CodeMap, but I don’t know how to implement it. Or just add appropriate checkbox somewhere in Expander UI.

### CODE REVIEW

**Comment by oleg-shilo** [comment]
I can do "VS Tools>Options>CodeMap". It's not a problem.

I am curious about something else in your branch. Have you noticed this strange NullRefon loading the extension under the debugger?

image

My master branch does not exhibit the same behaviour. The only difference between yours and mine is that you packed the assets there. I am not sure if it was deliberate from your site.
Removing the asset does not break the build. Not sure if it impacts the runtime behaviour.
Do you know anything about that?

**Comment by vsopko** [comment]
> Do you know anything about that?
I don't know, may be the project or manifest files becomes corrupted on my side while experiments. Just skip them and take cs+xaml. Thats should be enought to show bookmarks lines on scroll bar.

**Comment by oleg-shilo** [comment]
Hm...
I just tried your branch again and again. 

Removed the only asset (MEF) you had there. Let's assume for now that it was accidentally added. I was able to build. At runtime, there is no error. But I do not see bookmarks rendered. So maybe it's somehow needed.

May I ask you to just repeat what I described and see if indeed the absence of that asset interferes with the rendering? Or maybe it is something else.

I am OK to keep the asset but would prefer to avoid including it if it's not required. 

This is the manifest change that causing that inconvenience (null-ref when trying to access some unknown URL):

image

**Comment by vsopko** [comment]
I have VS 17.9.6 professional and no errors in debug with extension. Please try to add empty margin from template to test could they work on your side. To do this right click on project. select "Add" from context menu, then New Item > C# Items > Extensibility > Editor margin. May be on branch without this PR files
image

**Comment by oleg-shilo** [comment]
All good. The asset in question is added by the add-file wizard.
merging it now.

**Pull request merged**
